[package]
name = "lifeblox/t"
description = "A Runtime Typechecker for Roblox"
version = "0.1.0"
license = "MIT"
authors = ["Osyris", "life-media"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["*"]
include = ["lib", "lib/init.lua", "default.project.json", "LICENSE", "README.md", "wally.toml"]

[dependencies]
